-- RELATÓRIO DE PRODUTOS

SET PAGESIZE 200
SET LINESIZE 200

COLUMN ID            HEADING 'CÓDIGO'       FORMAT 9999
COLUMN NOME          HEADING 'PRODUTO'      FORMAT A30
COLUMN PRECO         HEADING 'PREÇO (R$)'   FORMAT 99990.99
COLUMN ESTOQUE       HEADING 'ESTOQUE'      FORMAT 9999
COLUMN DATA_CADASTRO HEADING 'DATA CAD.'    FORMAT A12

SET VERIFY OFF

accept v_nome char prompt 'Digite nome: ';
SELECT 
    ID,
    NOME,
    PRECO,
    ESTOQUE,
    TO_CHAR(DATA_CADASTRO, 'DD/MM/YYYY') AS DATA_CADASTRO
FROM PRODUTO
where upper(nome) like '%'|| upper('&v_nome') || '%'
ORDER BY ID;



